[colors]
[colors.primary]
background = '#1a1a22'
foreground = '#ffffff'

[colors.normal]
black   = "#1a1a22"
red     = "#ff5555"
green   = "#50fa7b"
yellow  = "#f1fa8c"
blue    = "#0096ff"
magenta = "#bd93f9"
cyan    = "#8be9fd"
white   = "#f8f8f2"

[colors.bright]
black   = "#6272a4"
red     = "#ff6e6e"
green   = "#69ff94"
yellow  = "#ffffa5"
blue    = "#3daeff"
magenta = "#d6acff"
cyan    = "#a4ffff"
white   = "#ffffff"

[colors.cursor]
text   = "#1a1a22"
cursor = "#0096ff"
